In [1]:
import pandas as pd

movies = pd.read_csv("tmdb_5000_movies.csv")
credits = pd.read_csv("tmdb_5000_credits.csv")

In [2]:
movies = movies.merge(credits, on="title")
movies.shape
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [3]:
# import ast

# x = movies["genres"].iloc[0]

# genres = ast.literal_eval(x)

# print(genres)
# print(type(genres))

In [4]:
# for i in genres:
#     print(i["name"])

In [5]:
import ast

def convert(obj):
    L = []

    obj = ast.literal_eval(obj)

    for item in obj:
        L.append(item["name"])

    return L

In [6]:
movies["genres"] = movies["genres"].apply(convert)

In [7]:
movies["genres"].head()

0    [Action, Adventure, Fantasy, Science Fiction]
1                     [Adventure, Fantasy, Action]
2                       [Action, Adventure, Crime]
3                 [Action, Crime, Drama, Thriller]
4             [Action, Adventure, Science Fiction]
Name: genres, dtype: object

In [8]:
movies["keywords"] = movies["keywords"].apply(convert)

In [9]:
movies["cast"].iloc[0]

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

In [10]:
def convert3(obj):
    L = []
    obj = ast.literal_eval(obj)
    count = 0

    for item in obj:
        L.append(item["name"])
        count += 1

        if count == 3:
            break

    return L

In [11]:
movies["cast"] = movies["cast"].apply(convert3)

In [12]:
movies[["title", "cast"]].head()

,title,cast
0,Avatar,"[Sam Worthington, Zoe Saldana, Sigourney Weaver]"
1,Pirates of the Caribbean: At World's End,"[Johnny Depp, Orlando Bloom, Keira Knightley]"
2,Spectre,"[Daniel Craig, Christoph Waltz, Léa Seydoux]"
3,The Dark Knight Rises,"[Christian Bale, Michael Caine, Gary Oldman]"
4,John Carter,"[Taylor Kitsch, Lynn Collins, Samantha Morton]"

In [13]:
movies['crew'].head()

0    [{"credit_id": "52fe48009251416c750aca23", "de...
1    [{"credit_id": "52fe4232c3a36847f800b579", "de...
2    [{"credit_id": "54805967c3a36829b5002c41", "de...
3    [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4    [{"credit_id": "52fe479ac3a36847f813eaa3", "de...
Name: crew, dtype: str

In [14]:
def fetch_director(obj):
    L = []

    obj = ast.literal_eval(obj)

    for item in obj:
        if(item['job']== "Director"):
            L.append(item["name"])
        
    return L;

In [15]:
movies["crew"] = movies["crew"].apply(fetch_director)

In [16]:
movies[["title", "genres", "keywords", "cast", "crew"]].head()

,title,genres,keywords,cast,crew
0,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [17]:
movies[movies['overview'].isnull()]

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
2658,15000000,[Drama],NaN,370980,"[pope, biography]",it,Chiamatemi Francesco - Il Papa della gente,NaN,0.738646,"[{""name"": ""Taodue Film"", ""id"": 45724}]",...,NaN,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,NaN,Chiamatemi Francesco - Il Papa della gente,7.3,12,370980,"[Rodrigo de la Serna, Sergio Hernández, Àlex B...",[Daniele Luchetti]
4145,2,[Documentary],NaN,459488,"[music, actors, legendary perfomer, classic ho...",en,"To Be Frank, Sinatra at 100",NaN,0.050625,"[{""name"": ""Eyeline Entertainment"", ""id"": 60343}]",...,NaN,[],Released,NaN,"To Be Frank, Sinatra at 100",0.0,0,459488,[Tony Oppedisano],[Simon Napier-Bell]
4437,913000,[Documentary],NaN,292539,[],de,Food Chains,NaN,0.795698,[],...,83.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,Food Chains,7.4,8,292539,[],[Sanjay Rawal]

In [18]:
movies['overview'] = movies['overview'].apply(
    lambda x: x.split() if isinstance(x, str) else []
)

In [19]:
movies['genres'] = movies['genres'].apply(
    lambda x: [i.replace(" ", "") for i in x]
)

In [20]:
movies['tags'] = (
    movies['overview']
    + movies['genres']
    + movies['keywords']
    + movies['cast']
    + movies['crew']
)

In [21]:
new_df = movies[['movie_id', 'title', 'tags']]  
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [22]:
new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

In [23]:
new_df['tags'] = new_df['tags'].apply(lambda x: x.lower())

In [24]:
new_df['tags'].iloc[0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction culture clash future space war space colony society space travel futuristic romance space alien tribe alien planet cgi marine soldier battle love affair anti war power relations mind and soul 3d sam worthington zoe saldana sigourney weaver james cameron'

In [25]:
from nltk.stem.porter import PorterStemmer

ps = PorterStemmer()

In [26]:
def stem(text):
    y = []

    for i in text.split():
        y.append(ps.stem(i))

    return " ".join(y)

In [27]:
new_df['tags'] = new_df['tags'].apply(stem)

In [28]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(
    max_features=5000,
    stop_words='english'
)

In [29]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [30]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zooey', 'zucker', 'zwick'],
      shape=(5000,), dtype=object)

In [31]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vectors)
similarity.shape
similarity[0]

array([1.        , 0.06737215, 0.06598289, ..., 0.04435328, 0.03265986,
       0.        ], shape=(4809,))

In [32]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]

    distances = similarity[movie_index]

    movies_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x: x[1]
    )[1:6]

    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [33]:
recommend('Avatar')

Aliens
Silent Running
Moonraker
Alien
Alien³

In [67]:
# V2 -of project - multiple movie input 

liked_movies = [
    'Iron Man 2',
    'The Dark Knight',
    'The Avengers'
    'Man of Steel'
]

In [68]:
movie_indices = []
missing_movies = []

for movie in liked_movies:
    matches = new_df.index[
        new_df["title"].str.strip().str.casefold() == movie.strip().casefold()
    ]

    if not matches.empty:
        movie_indices.append(matches[0])
    else:
        missing_movies.append(movie)

print("Missing movies:", missing_movies)

Missing movies: ['The AvengersMan of Steel']

In [69]:
liked_vectors = []

for idx in movie_indices:
    liked_vectors.append(vectors[idx])

In [70]:
import numpy as np;

In [71]:
user_vector = np.mean(liked_vectors, axis=0)

In [72]:
user_vector = user_vector.reshape(1, -1)

In [73]:
distances = cosine_similarity(
    user_vector,
    vectors
)

In [74]:
movies_list = list(enumerate(distances[0]))
movies_list = sorted(
    movies_list,
    reverse=True,
    key=lambda x: x[1]
)

In [75]:
# Remove already selected movies
for i in movies_list:
    movie_idx = i[0]

    if movie_idx not in movie_indices:
        print(new_df.iloc[movie_idx].title)

Batman Begins
The Dark Knight Rises
Batman
Batman
Iron Man 3
Superman
Avengers: Age of Ultron
Ant-Man
Iron Man
The Wolverine
Batman v Superman: Dawn of Justice
Superman Returns
Batman Forever
The Incredible Hulk
Batman & Robin
Batman Returns
Gangster's Paradise: Jerusalema
Thor
X2
Sexy Beast
X-Men: Apocalypse
Kick-Ass
The Shadow
The Amazing Spider-Man
10th & Wolf
Code of Honor
The Avengers
Harsh Times
Kick-Ass 2
Superman III
Sherlock Holmes: A Game of Shadows
Captain America: Civil War
Punisher: War Zone
City By The Sea
Deadpool
Dick Tracy
Flying By
Captain America: The First Avenger
Rockaway
Defendor
Spider-Man 2
X-Men
Micmacs
The Incredibles
The Godfather
Gran Torino
Thor: The Dark World
The Adventures of Elmo in Grouchland
Kiss of Death
All Is Lost
Me You and Five Bucks
Krrish
The Animal
Super
American Hero
Suicide Squad
X-Men: The Last Stand
Juliet and Alfa Romeo
Man of Steel
3 Days to Kill
Superman II
The Usual Suspects
Copying Beethoven
The Truman Show
Blue Like Jazz
Law Abiding Citizen
Harry Potter and the Philosopher's Stone
Batman: The Dark Knight Returns, Part 2
X-Men: First Class
Red Sonja
Wild Target
The Peanuts Movie
1982
Perrier’s Bounty
Rumble in the Bronx
My Super Ex-Girlfriend
King's Ransom
Pain & Gain
American Psycho
The Whole Ten Yards
J. Edgar
Faster
Lord of War
The R.M.
Small Apartments
Should've Been Romeo
Pound of Flesh
The Legend of Hercules
I Origins
The Diving Bell and the Butterfly
The 51st State
The Beastmaster
Chappie
The Replacement Killers
Homefront
Madison
Unbreakable
Ajami
Chasing Amy
X-Men Origins: Wolverine
Frequency
Shinjuku Incident
Auto Focus
Payback
Robot & Frank
Riddick
RED
Half Past Dead
A Christmas Carol
Hancock
The Amazing Spider-Man 2
The Godfather: Part III
Amidst the Devil's Wings
Machine Gun McCain
Hannibal Rising
We Are Your Friends
How to Fall in Love
Le Havre
The Phantom
Megamind
Behind Enemy Lines
After Earth
Killers
I Am Number Four
The Last Emperor
Son of God
The Image Revolution
Stripes
A Beautiful Mind
The Mask of Zorro
The Four Feathers
12 Rounds
I Served the King of England
Only God Forgives
Garden State
Charlie St. Cloud
The Shipping News
The Adventurer: The Curse of the Midas Box
Interview with the Assassin
Khumba
A Guy Thing
Apocalypto
Barbecue
Idlewild
Highlander
From Russia with Love
The Sweeney
The Verdict
Dutch Kills
Letters to God
Firestorm
Memento
Fantastic 4: Rise of the Silver Surfer
Zero Effect
Black Mass
Fantastic Four
Big Fish
Hart's War
Harry Brown
The Big Hit
Commando
The Spirit
Dead Man Down
Nicholas Nickleby
Manito
The Other Side of Heaven
Last Orders
Futuro Beach
Ghost Rider
Sinister
Everything Must Go
Spider-Man 3
Birdman
Batman
Disturbia
The Talented Mr. Ripley
Quantum of Solace
About Schmidt
At First Sight
Griff the Invisible
Salton Sea
Rust
Lethal Weapon 4
What's the Worst That Could Happen?
Jeff, Who Lives at Home
Clash of the Titans
Point Blank
Imagine That
From Paris with Love
Young Sherlock Holmes
Batman
Blue Ruin
Teenage Mutant Ninja Turtles: Out of the Shadows
Little Big Top
Frat Party
Southpaw
The Mexican
Hellraiser
The Cookout
Light Sleeper
Close Range
Ali
Alfie
Spawn
Action Jackson
I Love Your Work
The Best Man
Prisoners
The Punisher
Dungeons & Dragons: Wrath of the Dragon God
The Secret in Their Eyes
Teenage Mutant Ninja Turtles
The Judge
Watchmen
Nine
Synecdoche, New York
Nightcrawler
The Masked Saint
Don McKay
Secret Window
Inspector Gadget
Reign Over Me
Gladiator
Bizarre
Bruce Almighty
Confidence
Easy Money
Blood Ties
The Killer Inside Me
Superman IV: The Quest for Peace
The Eclipse
Flywheel
Liar Liar
In the Name of the King: A Dungeon Siege Tale
The Good Night
2:13
The Gunman
Heaven is for Real
Resurrecting the Champ
Steel
Spider
Owning Mahowny
The Barbarian Invasions
Everybody's Fine
Repo Men
Take Me Home Tonight
Captain America: The Winter Soldier
True Lies
Austin Powers in Goldmember
White House Down
Mystery Men
Wish I Was Here
Wanted
Snitch
Bottle Rocket
American Sniper
Rosewater
Days of Thunder
Get Carter
Timecop
In the Name of the King III
Tin Can Man
The Equalizer
A Low Down Dirty Shame
I Hope They Serve Beer in Hell
The Patriot
Little Nicky
Half Nelson
My All American
Green Street Hooligans: Underground
Hell's Angels
The Ant Bully
Moby Dick
Ladder 49
Paranormal Activity: The Marked Ones
Bronson
Stardust
Multiplicity
The Transporter
The Perfect Host
Inception
Forsaken
Loose Cannons
The Hunt
Road to Perdition
Just Looking
El Mariachi
Swingers
Jingle All the Way
Master and Commander: The Far Side of the World
The Ladies Man
The Mudge Boy
Eragon
Getaway
Dead Man's Shoes
The Rocket: The Legend of Rocket Richard
Cradle 2 the Grave
Home Alone 2: Lost in New York
The Sorcerer's Apprentice
Gangster Squad
The Counselor
The Village
Nixon
X-Men: Days of Future Past
High Road
About Time
Raging Bull
The Ghost Writer
Urbania
Let's Go to Prison
The Yards
Pootie Tang
Youth in Revolt
The Firm
Boogeyman
40 Days and 40 Nights
Grandma's Boy
Love Happens
Street Fighter: The Legend of Chun-Li
The Torture Chamber of Dr. Sadism
Se7en
I Married a Strange Person!
The Last King of Scotland
Breakdown
Casino Royale
Saint Ralph
Curse of the Golden Flower
Thunder and the House of Magic
American Splendor
Flubber
We Bought a Zoo
Underdogs
Rush Hour 3
Kindergarten Cop
The Book of Life
Scarface
Hide and Seek
The Love Guru
Sky High
Green Lantern
The Good German
Three Kingdoms: Resurrection of the Dragon
21 & Over
The Man in the Iron Mask
The Gambler
Madea's Witness Protection
Phantasm II
A Dog Of Flanders
Hang 'em High
Hitman
Hugo
Contraband
Disclosure
Abduction
Alatriste
Spy Game
Seven Years in Tibet
Hesher
Public Enemies
The Best Offer
Driven
The Jackal
N-Secure
Dude Where's My Dog?
Mrs. Doubtfire
Big Trouble in Little China
Con Air
Alien Zone
Killing Zoe
Thinner
Deadfall
The Living Wake
Flipper
Chuck & Buck
Rise of the Planet of the Apes
Taken 3
Guardians of the Galaxy
Blood and Wine
The Bad Lieutenant: Port of Call - New Orleans
Brother
Seeking a Friend for the End of the World
The Son of No One
Crank
The Damned United
Atlas Shrugged Part III: Who is John Galt?
This Is England
Tycoon
Out of the Blue
The Town
Ironclad
Edmond
The Glimmer Man
Capote
Buffalo '66
The Legend of Zorro
Wasabi
Saw III
Cavite
What Just Happened
Enter the Void
Crimson Tide
Hamlet
Whiteout
The Count of Monte Cristo
Cloudy with a Chance of Meatballs 2
Split Second
Elizabethtown
Pulp Fiction
Beyond the Sea
Six-String Samurai
Shame
In the Valley of Elah
Rotor DR1
The Family Man
Nothing to Lose
I Love You, Beth Cooper
The Shawshank Redemption
Shutter Island
Collateral
Hercules
I Am Wrath
Stitches
Trees Lounge
Licence to Kill
Celebrity
8 Heads in a Duffel Bag
I Love You, Man
Street Kings
Little Boy
You Only Live Twice
Butterfly
Memoirs of an Invisible Man
From Here to Eternity
Alexander and the Terrible, Horrible, No Good, Very Bad Day
Ninja Assassin
To Save A Life
The Number 23
My Cousin Vinny
Jarhead
A Turtle's Tale: Sammy's Adventures
The Singing Detective
Cheap Thrills
ABCD (Any Body Can Dance)
Transformers: Revenge of the Fallen
Walking Tall
Eraserhead
Two Lovers
Certifiably Jonathan
Alexander's Ragtime Band
Treading Water
Need for Speed
The Fugitive
Fabled
Hurricane Streets
Smoke Signals
Special
El Rey de Najayo
Gangs of New York
Hollywood Shuffle
A Civil Action
Black Water Transit
Cat on a Hot Tin Roof
London to Brighton
America Is Still the Place
The Hunted
American Gangster
Bedazzled
Dirty Grandpa
The Astronaut Farmer
Made
Alexander
The Call of Cthulhu
Bully
The Ice Storm
All Hat
Crocodile Dundee in Los Angeles
Elektra
Rampage
And So It Goes
What's Eating Gilbert Grape
Ocean's Twelve
Heli
The 41–Year–Old Virgin Who Knocked Up Sarah Marshall and Felt Superbad About It
True Grit
The Pursuit of Happyness
Slam
Vanilla Sky
I Love You Phillip Morris
Dom Hemingway
Ocean's Eleven
There Be Dragons
Stealing Harvard
Forrest Gump
Muppets Most Wanted
The Cold Light of Day
Casino Jack
Cyrus
Return of the Living Dead 3
Monkeybone
A Dangerous Method
Fort McCoy
Eternal Sunshine of the Spotless Mind
Bran Nue Dae
Maximum Risk
Queen of the Damned
Home Fries
The Bounty
GoodFellas
Flight
Back to the Future
The Grace Card
Fun with Dick and Jane
Adulterers
War of the Worlds
The Watcher
Furious 7
Journey to the Center of the Earth
Freddy Got Fingered
Frost/Nixon
The Game Plan
Paul
Extraordinary Measures
12 Years a Slave
Mi America
Identity Thief
Awake
Elling
Zoom
Man on a Ledge
Unknown
Grosse Pointe Blank
Hellboy II: The Golden Army
Time Changer
Enemy of the State
Mission: Impossible III
All That Jazz
American Hustle
Alex Cross
Dredd
The Ladykillers
Superhero Movie
Once Upon a Time in America
Malevolence
Recess: School's Out
Bound by Honor
The Mummy: Tomb of the Dragon Emperor
The Art of War
Racing Stripes
There Will Be Blood
20 Dates
Free State of Jones
Compadres
Deadline - U.S.A.
Inescapable
Zulu
Stolen
The Namesake
The Iceman
Flash of Genius
Air Force One
Locker 13
Jack Brooks: Monster Slayer
War Horse
The Karate Kid
The SpongeBob SquarePants Movie
An Unfinished Life
Now You See Me 2
The Young Messiah
The Man
Dragonball Evolution
High Fidelity
Swelter
The Three Burials of Melquiades Estrada
The Haunted Mansion
Willard
Kiss Kiss Bang Bang
The Fan
The Protector
The Pallbearer
Stranded
Chasing Papi
All the King's Men
Taxi Driver
Confessions of a Dangerous Mind
Sweet November
Assassins
I Come with the Rain
The Pledge
In Cold Blood
The Score
The International
The Death and Life of Bobby Z
3:10 to Yuma
Get Shorty
Knowing
The Newton Boys
The Boy in the Striped Pyjamas
State of Play
Nowhere Boy
Edge of Darkness
Adaptation.
Reindeer Games
The Jimmy Show
Windsor Drive
The Sound and the Shadow
The Wraith
Kung Fu Panda 2
The Adjustment Bureau
River's Edge
Run All Night
Mondays in the Sun
Cold Mountain
Cape Fear
Hulk
All the Pretty Horses
3 Strikes
A Knight's Tale
On the Waterfront
You, Me and Dupree
Somewhere
Fantastic Mr. Fox
Tombstone
Freeze Frame
We Own the Night
Amnesiac
Bedtime Stories
Me Before You
The Last Days on Mars
Smiling Fish & Goat On Fire
Young Frankenstein
The Water Diviner
Out of the Blue
Song One
2 Guns
Hoffa
The Whole Nine Yards
300
Baahubali: The Beginning
The Perfect Wave
MacGruber
Raising Victor Vargas
Hayride
Pinocchio
The Legend of Drunken Master
Rocket Singh: Salesman of the Year
The Claim
A Thin Line Between Love and Hate
Men in Black 3
Airborne
Sin City: A Dame to Kill For
Romeo Is Bleeding
Free Style
Dum Maaro Dum
Angela's Ashes
The Devil's Double
The Night Visitor
Lady in the Water
The Chambermaid on the Titanic
Latter Days
Taking Woodstock
Die Hard: With a Vengeance
Exit Wounds
The Book of Eli
Due Date
Kickboxer: Vengeance
Frailty
The Transporter Refueled
Room
Vacation
The Crying Game
Jab Tak Hai Jaan
Sky Captain and the World of Tomorrow
She's All That
Tadpole
54
Napoleon Dynamite
Death to Smoochy
The Bone Collector
The Place Beyond the Pines
Antwone Fisher
Fight to the Finish
Departure
The Green Hornet
Fool's Gold
Oblivion
Ride Along
Alone in the Dark
Kites
Home Run
Sin City
Tinker Tailor Soldier Spy
Never Back Down
The Informant!
Megiddo: The Omega Code 2
Solitary Man
Cotton Comes to Harlem
Lonesome Jim
Death Sentence
The Lego Movie
Undisputed
Thir13en Ghosts
Good Morning, Vietnam
All About the Benjamins
Mr. Popper's Penguins
I Want Someone to Eat Cheese With
E.T. the Extra-Terrestrial
Unleashed
8MM
Coriolanus
Gods and Monsters
Underworld: Rise of the Lycans
Drive Hard
Heist
Journey 2: The Mysterious Island
Jersey Girl
Die Another Day
Maze Runner: The Scorch Trials
Legend
W.
Johnny English Reborn
Better Luck Tomorrow
The Taking of Pelham 1 2 3
Wristcutters: A Love Story
Catch Me If You Can
DysFunktional Family
Submarine
Spy Kids 3-D: Game Over
F.I.S.T.
Barry Munday
The Ballad of Gregorio Cortez
The Pursuit of D.B. Cooper
Date Movie
The Book of Mormon Movie, Volume 1: The Journey
Eraser
Dr. No
Get Over It
Robin Hood
Hostage
Legal Eagles
RockNRolla
A Good Year
The Illusionist
Mo' Better Blues
Million Dollar Baby
The Master of Disguise
Quigley Down Under
Mad Max: Fury Road
Winter Passing
The Mighty Ducks
Finding Forrester
The Other Guys
The Proposition
Star Wars: Episode II - Attack of the Clones
Total Recall
The Tale of Despereaux
TMNT
Baby Boy
Tango & Cash
My Boss's Daughter
Teen Wolf Too
Inkheart
The Man from Snowy River
The Brown Bunny
Taken 2
The Straight Story
Get Rich or Die Tryin'
Trash
The Hurricane
The Business of Fancydancing
Puss in Boots
R.I.P.D.
Star Trek V: The Final Frontier
Cellular
Land of the Lost
Hudson Hawk
The Emperor's Club
Lone Star
The Manchurian Candidate
Double Impact
Joe Somebody
Shaft
The Last Station
Invaders from Mars
Straight Out of Brooklyn
Jerry Maguire
Basic
Broken City
Stomp the Yard
Roadside Romeo
Pompeii
The Dead Zone
Soul Kitchen
Thumbsucker
RED 2
School for Scoundrels
The Kite Runner
51 Birch Street
The NeverEnding Story
Untraceable
Mambo Italiano
The Midnight Meat Train
Take the Lead
Slow Burn
Def Jam's How to Be a Player
The Fighter
The Lost Weekend
Into the Wild
Dark Blue
The Imitation Game
The Lincoln Lawyer
A Haunted House 2
London
Nine Queens
The Guilt Trip
John Carter
Warcraft
Home Alone
Kung Fu Panda 3
A Walk Among the Tombstones
Drive
The Apostle
Black November
The Way of the Gun
The Grandmaster
Flyboys
The Good Thief
Harry Potter and the Order of the Phoenix
Bringing Out the Dead
Training Day
The Legend of Tarzan
Clay Pigeons
Thunderball
Harley Davidson and the Marlboro Man
Battle: Los Angeles
Mr. Holland's Opus
The Scorpion King
Down Terrace
Jimmy Neutron: Boy Genius
Below Zero
Surrogates
A Woman, a Gun and a Noodle Shop
Without Limits
Fear and Loathing in Las Vegas
Killing Them Softly
Wolves
Faith Like Potatoes
Kicking & Screaming
Barbershop
The Last Temptation of Christ
A Nightmare on Elm Street 4: The Dream Master
Wicker Park
War
Stop-Loss
Agora
Tae Guk Gi: The Brotherhood of War
One to Another
Speed Racer
Out of the Furnace
Fifty Dead Men Walking
The Last Witch Hunter
Delgo
The Nut Job
Driving Lessons
Swordfish
The Way Way Back
The Railway Man
Videodrome
The Cable Guy
The Skulls
Righteous Kill
Street Fighter
Mandela: Long Walk to Freedom
The First Great Train Robbery
Henry & Me
Ghost Rider: Spirit of Vengeance
The Little Vampire
Insurgent
Paparazzi
The Young Unknowns
Drive Angry
Road Hard
Nighthawks
Brazil
Star Trek Into Darkness
Adam
The 5th Quarter
Blow Out
Deuce Bigalow: Male Gigolo
Our Kind of Traitor
Hav Plenty
The Boxtrolls
The Limey
Fateless
The Edge
A View to a Kill
In the Company of Men
My Name Is Khan
Mission: Impossible II
Catwoman
The Lost World: Jurassic Park
My Dog Skip
Penitentiary
Lawrence of Arabia
The Sentinel
Patriot Games
30 Minutes or Less
Kingdom of Heaven
Teenage Mutant Ninja Turtles II: The Secret of the Ooze
The November Man
The Puffy Chair
The Bourne Supremacy
Dracula Untold
Killer Elite
Clockstoppers
The Night Listener
Silver Linings Playbook
The Great Beauty
An Ideal Husband
R100
The Loss of Sexual Innocence
Harry Potter and the Goblet of Fire
Gods and Generals
The Mask
Only the Strong
RoboCop 3
Betty Fisher and Other Stories
Dragonfly
Down to Earth
Mr. Turner
Saw V
The Musketeer
Transporter 2
The Spy Next Door
Seven Psychopaths
Cinderella Man
A Serious Man
Snow Dogs
Double Take
The Silence of the Lambs
Layer Cake
Maurice
Nothing But a Man
Collateral Damage
Analyze This
Paul Blart: Mall Cop
Pandaemonium
Desert Dancer
High Anxiety
Saw
The Hammer
Tarnation
The Rookie
American History X
Mission: Impossible
The Woman in Black
Scrooged
Buffalo Soldiers
Good Kill
The Rundown
A History of Violence
The Sting
The Elephant Man
Jack the Giant Slayer
Firewall
Parker
Man of the Year
The Last Time I Committed Suicide
Hum To Mohabbat Karega
Shanghai Calling
Safe
Cop Land
The Brain That Wouldn't Die
Chicago
Donnie Brasco
The Young and Prodigious T.S. Spivet
Kicks
Creative Control
Lone Wolf McQuade
The Secret of Kells
Goldfinger
The Good Heart
Rang De Basanti
Asterix at the Olympic Games
Hit & Run
Crank: High Voltage
Ong Bak 2
Spring Breakers
Repo Man
Dark City
Soul Plane
The Jerky Boys
The Maze Runner
Lucky Number Slevin
Bad Santa
A Single Man
Cliffhanger
Outside Providence
Stormbreaker
1911
Ishtar
Rescue Dawn
A Million Ways to Die in the West
Redbelt
Mad City
Rambo III
RoboCop
Reign of Fire
Steamboy
Prison
Shrek Forever After
L.A. Confidential
The Lord of the Rings: The Fellowship of the Ring
The Hunting Party
Rocky Balboa
Diamonds Are Forever
The Santa Clause 2
East Is East
Men of War
The Losers
The Last Godfather
I Spit on Your Grave
The Last Shot
The Baader Meinhof Complex
Legend of a Rabbit
Billy Elliot
Safe Men
Creepshow
Boomerang
Little Nicholas
Wall Street
Our Idiot Brother
Flight of the Intruder
The Matrix Reloaded
Winter's Tale
The Godfather: Part II
xXx
Striptease
Troy
Fury
Shaun of the Dead
The Martian
Focus
Snowpiercer
The Thirteenth Floor
Transformers: Age of Extinction
Ocean's Thirteen
First Knight
Money Train
Extremely Loud & Incredibly Close
Nancy Drew
The Nutty Professor
Dear Frankie
Battleship
Bridge of Spies
3 Ninjas Kick Back
Excessive Force
Downfall
Analyze That
About a Boy
Observe and Report
The Front Page
Good Deeds
London Has Fallen
Stuart Little
Star Trek III: The Search for Spock
Live and Let Die
Do You Believe?
Last I Heard
Jonah Hex
Miss Congeniality
Kung Fu Jungle
Gun Shy
Wah-Wah
Moon
Max
An Everlasting Piece
The Betrayed
Sahara
The Haunting in Connecticut 2: Ghosts of Georgia
The Wood
Oldboy
Moonlight Mile
First Blood
Hobo with a Shotgun
The Last Stand
The Legend of the Lone Ranger
Movie 43
The Opposite Sex
Next Day Air
The Ugly Truth
Jefferson in Paris
Thank You for Smoking
Don Juan DeMarco
Willy Wonka & the Chocolate Factory
Desperado
House of D
A Funny Thing Happened on the Way to the Forum
Indiana Jones and the Kingdom of the Crystal Skull
The Man from U.N.C.L.E.
Blade: Trinity
Antitrust
Spy Hard
The Emperor's New Groove
Get Hard
Dudley Do-Right
Bubble Boy
Blow
What to Expect When You're Expecting
Torque
The Beaver
A Most Violent Year
Orgazmo
Match Point
Bon Cop Bad Cop
The Great Gatsby
Sinbad: Legend of the Seven Seas
The Lady from Shanghai
Spectre
Renaissance
Witness
Inside Llewyn Davis
Bright Star
Black Nativity
Plastic
The Ridiculous 6
Looper
Along Came Polly
Up in the Air
Click
3000 Miles to Graceland
Ride Along 2
Red Tails
In the Land of Women
The Egyptian
My Beautiful Laundrette
Casper
Absolute Power
The Wrestler
Shakespeare in Love
S.W.A.T.
Fat, Sick & Nearly Dead
The Island
The Sitter
K-PAX
The Untouchables
Misconduct
A Thousand Words
In Too Deep
Die Hard
Midnight Cowboy
Spider-Man
Code Name: The Cleaner
Skin Trade
The River Wild
Mortal Kombat
On Her Majesty's Secret Service
Live Free or Die Hard
Hot Rod
The Libertine
Life as a House
Machete
Paa
G.I. Joe: Retaliation
Salvation Boulevard
Captive
Secret in Their Eyes
Minions
End of the Spear
Flirting with Disaster
Pride and Glory
The Remains of the Day
Don Jon
Thunderbirds
Stuart Little 2
Runaway Bride
The End of the Affair
Alex & Emma
Bolt
Tomorrow Never Dies
Bang
V for Vendetta
15 Minutes
The Constant Gardener
De-Lovely
War, Inc.
Two Evil Eyes
Zipper
EuroTrip
Chain of Command
Caravans
The Jacket
Hands of Stone
I'm Not There.
The Debt
TRON: Legacy
Rob Roy
In Good Company
Boys Don't Cry
The Saint
Ca$h
Mission: Impossible - Ghost Protocol
Paddington
School of Rock
Gentlemen Broncos
Tank Girl
Original Sin
Robin and Marian
Criminal
8 Mile
A Nightmare on Elm Street 3: Dream Warriors
Surf's Up
Toy Story 2
The Legend of Bagger Vance
Solaris
Partition
The Return of the Pink Panther
Sublime
Arthur and the Invisibles
Gone Girl
Imaginary Heroes
Iguana
Judgment at Nuremberg
Firestarter
The I Inside
The King's Speech
Class of 1984
Paris, je t'aime
Divergent
Top Cat Begins
Dying of the Light
The Wash
2001: A Space Odyssey
Alone With Her
You Don't Mess with the Zohan
Just Like Heaven
Atonement
ParaNorman
Kate & Leopold
Infamous
Jimmy and Judy
Krull
Find Me Guilty
Black or White
My Favorite Martian
The Adventures of Sharkboy and Lavagirl
Playing for Keeps
Machete Kills
Character
Lords of London
Nerve
Grand Theft Parsons
Pirates of the Caribbean: On Stranger Tides
Beastly
Starship Troopers
Why I Did (Not) Eat My Father
Kansas City